//
//  Blur.swift
//  ABJC
//
//  Created by Noah Kamara on 26.03.21.
//

import SwiftUI

<<<<<<< HEAD:ABJC/UI/Subviews/Utility/Blur.swift
public struct Blur: UIViewRepresentable {
    var style: UIBlurEffect.Style = .prominent
    
=======
struct Blur: View {
    var body: some View {
        LegacyBlur()
    }
}

struct Blur_Previews: PreviewProvider {
    static var previews: some View {
        Blur()
    }
}

public struct LegacyBlur: UIViewRepresentable {
    var style: UIBlurEffect.Style = .prominent

>>>>>>> parent of 78afc87 (Rewrote App to utilise autogenerated jellyfin api):ABJC tvOS/UI/Components/Materials/Blur.swift
    public init(_ style: UIBlurEffect.Style = .regular) {
        self.style = style
    }
    
    public func makeUIView(context: Context) -> UIVisualEffectView {
        return UIVisualEffectView(effect: UIBlurEffect(style: style))
    }
    
    public func updateUIView(_ uiView: UIVisualEffectView, context: Context) {
        uiView.effect = UIBlurEffect(style: style)
    }
}

struct Blur_Previews: PreviewProvider {
    static var previews: some View {
        Blur()
            .previewDevice("Apple TV")
    }
}
