# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ABJC.xcodeproj")
    build_app(scheme: "ABJC tvOS")
    upload_to_testflight
  end

  desc "Run SwiftLint"
  lane :lint do 
    swiftlint(
      mode: :lint,
      output_file: "swiftlint.result.json", # The path of the output file (optional)
      # config_file: ".swiftlint.yml",     # The path of the configuration file (optional)
      raise_if_swiftlint_error: false,      # Allow fastlane to raise an error if swiftlint fails
      ignore_exit_status: true,    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
      reporter: "xcode",
    )
  end

  # desc "Run Tests"
  # lane :lint do 
  #   swiftlint(
  #     mode: :lint,
  #     output_file: "swiftlint.result.json", # The path of the output file (optional)
  #     # config_file: ".swiftlint.yml",     # The path of the configuration file (optional)
  #     raise_if_swiftlint_error: true,      # Allow fastlane to raise an error if swiftlint fails
  #     ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
  #     reporter: "xcode",
  #   )
  # end
end


