# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Push a new beta build to TestFlight"
  # lane :beta do
  #   increment_build_number(xcodeproj: "ABJC.xcodeproj")
  #   build_app(scheme: "ABJC tvOS")
  #   upload_to_testflight
  # end

  desc "Format Code with 'swiftformat'"
  lane :format do 
    # swiftformat(
    #   config: ".swiftformat"                # Path to configuration file (optional)
    #   dryrun: false,                                              # Run in dry mode (without actually changing any files) (optional)
    #   lint: true                                                  # Like `--dryrun`, but returns an error if formatting is needed (optional)
    # )
  end

  desc "Lint Code with 'swiftlint'"
  lane :lint do 
    swiftlint(
      mode: :lint,
      output_file: "swiftlint.result.json", # The path of the output file (optional)
      # config_file: ".swiftlint.yml",     # The path of the configuration file (optional)
      raise_if_swiftlint_error: false,      # Allow fastlane to raise an error if swiftlint fails
      ignore_exit_status: true,    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
      reporter: "xcode",
    )
  end

  desc "Run Tests"
  lane :test do 
    run_tests(
      workspace: "ABJC.xcworkspace",
      devices: ["Apple TV 4K (at 1080p) (2nd generation)"],
      scheme: "ABJC tvOS"
    )
  end

  desc "Create Screenshots"
  lane :snap do 
    capture_screenshots
  end

  # desc "Create Screenshots, Frame them & Upload to AppStore Connect"
  # lane :snap_deploy do 
  #   capture_screenshots
  # end
end


