# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "Apple TV",
  # "Apple TV 4K (2nd generation)",
])

# List of Locales to snap
# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] 
# ])


# Command Options
scheme("ABJC Snapshots") # Scheme
clear_previous_screenshots(true) # Clear old screenshots
output_directory("./screenshots") # Output Directory
html_template("fastlane/screenshots.html.erb") # HTML Template

# Appearance Options
override_status_bar(true) # 9:41 AM, full battery and reception
dark_mode(true) # Enable Dark Mode

# Debugging
stop_after_first_error(true)
headless(false)

