name: "Docker Compose Test"

      
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Checkout Developer-Utils
      uses: actions/checkout@v2
      with: 
        repository: "ABJC/Developer-Utilities"
        token: ${{ secrets.GH_TOKEN }}
        ref: "main"
        
    - name: Compose
      run: "cd Developer-Utilities/jellyfin-docker; docker-compose up"
  test:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
