name: 🧹 SwiftFormat 
on:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    name: Tests 
    runs-on: macos-11
      
    steps:      
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Select Xcode Version (13.0)
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
        
    - name: Install Dependencies
      run: "pod install"
            
    - name: Run Swiftformat 
      run: "Pods/SwiftFormat/CommandLineTool/swiftformat ."
