name: "Lint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Lint"
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Run SwiftLint
        run: swiftlint
