name: "Lint"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "LintLint"
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Run SwiftLint
        run: swiftlint
