name: Tests 
on:
  workflow_dispatch:
jobs:
  tests:
    name: Tests 
    runs-on: macos-11
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
        
    - name: Install Pods
      run: |
        pod install
            
    - name: Run tests 
      run: |
        bundle exec fastlane tests
