name: "🧪 UITests"
on:
  workflow_dispatch:
jobs:
  tests:
    name: Tests 
    runs-on: macos-11
      
    steps:
    - name: "Checkout Developer Utilities"
      uses: actions/checkout@v2
      with:
        repository: 'abjc/Developer-Utilities'
        ref: 'main'
        path: 'dev_utils'
      
    - uses: actions/cache@v2
      name: Cache
      with:
        path: dev_utils/jellyfin_docker/media
      
    - name: Docker Setup
      uses: docker-practice/actions-setup-docker@1.0.8
    
    - name: "Print DirTree"
      run: 'find . -type f -name "*.mkv"'
      
    - name: "Setup Media"
      run: "cd dev_utils/jellyfin_docker; ./setup.sh create; cd .."
      
    - name: Compose
      run: "sudo docker-compose -f dev_utils/jellyfin_docker/docker-compose.yml up -d"

    - name: "Check if Jellyfin Server did Boot"
      uses: mydea/action-wait-for-api@v1
      with:
        url: "http://localhost:8096/System/Ping"
        expected-status: 200
        
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
        
    - name: Install Pods
      run: |
        pod install
    
    - name: Test
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        action: test
        workspace: ABJC.xcworkspace
        scheme: "Github Actions"
        destination: platform=tvOS Simulator,OS=15.0,name=Apple TV 4K (at 1080p) (2nd generation)
        quiet: true
        enable-code-coverage: true
    
    - name: "Upload Coverage Report"
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
