name: Tests 
on:
  workflow_dispatch:
jobs:
  tests:
    name: Tests 
    runs-on: macos-11
      
    steps:
    - name: "Checkout Developer Utilities"
      uses: actions/checkout@v2
      with:
        repository: 'abjc/Developer-Utilities'
        ref: 'main'
        path: 'dev_utils'
        
    - name: "Print DirTree"
      run: "find -d ."
      
    - name: Docker Setup
      uses: docker-practice/actions-setup-docker@1.0.8
    
    - name: "LS"
      run: "ls"
      
    - name: "Navigate to jellyfin_docker"
      run: "cd dev_utils/jellyfin_docker; ./setup.sh; cd .."
      
    - name: Compose
      run: "sudo docker-compose -f dev_utils/jellyfin_docker/docker-compose.yml up -d"

    - name: "Check if Jellyfin Server did Boot"
      uses: mydea/action-wait-for-api@v1
      with:
        url: "http://localhost:8096/System/Ping"
        expected-status: 200
        
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
        
    - name: Install Pods
      run: |
        pod install
            
    - name: Run tests 
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'test'
